version: 0.2

env:
  secrets-manager:
    key: mutato/ssh:key

phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo -e "$key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git init
      - git remote add origin "git@github.com:${gitOwner}/${gitRepo}.git"
      - git clean -d  -f .
      - git checkout -f "origin/${gitBranch}"
      - git reset --hard "${gitCommit}"
  build:
    commands:
      - npm install test
      - npm run-script docs
      - git mv docs/* ./
      - git commit -am '[ci] - Deploy docs'
      - git push -f origin gh-pages
  post_build:
    commands:
      - echo 'Run integration tests'
      - echo "Don't for get to store artifacts"
