Description: Mutato CI Pipeline
Parameters:
  GithubOwner:
    Type: String
  GithubRepo:
    Type: String
  OauthToken:
    Type: String
  GithubBranch:
    Type: String
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
    DeletionPolicy: Delete
  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - !GetAtt ArtifactBucket.Arn
              - !Sub arn:${AWS::Partition}:s3:::${ArtifactBucket}/${CodePipeline}
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref AWS::StackName
      ServiceRole: !GetAtt CodePipelineCodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: docker.io/node:latest
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: !Ref GithubOwner
                Repo: !Ref GithubRepo
                PollForSourceChanges: true
                Branch: !Ref GithubBranch
                OAuthToken: !Ref OauthToken
              Name: SourceAction
              OutputArtifacts:
                - Name: repo
              RunOrder: 1
        - Name: Build
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProject
                PrimarySource: repo
              Name: BuildAction
              InputArtifacts:
                - Name: repo
              RunOrder: 1
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: MutatoPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:StopBuild
                  - codebuild:BatchGetBuilds
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Sub arn:${AWS::Partition}:s3:::${ArtifactBucket}/*
                  - !GetAtt CodeBuildProject.Arn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
  CodePipelineCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: Mutato-CodeBuild-Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - cloudformation:ValidateTemplate
                  - cloudformation:DescribeStacks
                  - s3:Get*
                  - s3:List*
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Sub arn:${AWS::Partition}:codebuild
                  - !Sub arn:${AWS::Partition}:s3:::${ArtifactBucket}/*
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
  OutputS3ArtifactBucket:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /stelligent/mutato/s3artifactbucket
      Type: String
      Value: !Ref ArtifactBucket
      Description: S3 Location of CI output artifacts for Mutato
  OutputCodePipelineName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /stelligent/mutato/codepipelinename
      Type: String
      Value: !Ref CodePipeline
      Description: Name of the Codepipeline for Mutato
  OutputCodeBuildName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /stelligent/mutato/codebuildproject
      Type: String
      Value: !Ref CodeBuildProject
      Description: Name of the Codebuild Project for Mutato
